apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-10-24T17:37:29Z"
  generation: 1
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
  resourceVersion: "2892579"
  uid: 3f75f12c-fd01-4d64-87c5-2a88c7356e27
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: currency-exchange
    spec:
      containers:
      - image: sarathkumar2810/mmv3-currency-exchange-service:0.0.11-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv3-currency-exchange-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-10-24T17:37:44Z"
    lastUpdateTime: "2024-10-24T17:37:44Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-10-24T17:37:29Z"
    lastUpdateTime: "2024-10-24T17:37:44Z"
    message: ReplicaSet "currency-exchange-6d7fcbdd85" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
  apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cloud.google.com/neg: '{"ingress":true}'
    creationTimestamp: "2024-10-24T17:39:32Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app: currency-exchange
    name: currency-exchange
    namespace: default
    resourceVersion: "2894129"
    uid: 756db1b2-e44d-46a5-b0db-6458ce6a57b5
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 34.118.235.228
    clusterIPs:
    - 34.118.235.228
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30569
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: currency-exchange
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 34.133.4.251
        ipMode: VIP
